name: Update Top Played SVG

on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00 UTC
  workflow_dispatch:     # allow manual runs too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Fetch Top Played JSON
        run: curl -s https://yye-spotify.onrender.com/api/top-played > top-played.json

      - name: Generate SVG
        run: |
          node -e "
            const fs = require('fs');
            const data = JSON.parse(fs.readFileSync('top-played.json', 'utf8'));
            const items = Array.isArray(data.items) ? data.items : [];
            const height = 60 + items.length * 30;
            let svg = \`<svg xmlns='http://www.w3.org/2000/svg' width='600' height='\${height}'>\`;
            svg += \`<style>text { font-family: sans-serif; font-size: 16px; }</style>\`;
            svg += \`<text x='10' y='30'>Top Played Tracks:</text>\`;
            if (items.length > 0) {
              items.forEach((item, i) => {
                const track = item.name || 'Unknown Track';
                const artists = item.artists && Array.isArray(item.artists)
                  ? item.artists.map(a => a.name).join(', ')
                  : 'Unknown Artist';
                const popularity = item.popularity ?? 'N/A';
                svg += \`<text x='10' y='\${60 + i * 30}'>\${track} by \${artists} (Popularity: \${popularity})</text>\`;
              });
            } else {
              svg += \`<text x='10' y='60'>No data available.</text>\`;
            }
            svg += \`</svg>\`;
            fs.writeFileSync('top-played.svg', svg);
          "

      - name: Commit & Push SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add top-played.svg
          git commit -m "Update top-played.svg [skip ci]" || echo "Nothing to commit"
          git push
