name: Update Top Played SVG

on:
  schedule:
    - cron: "0 0 * * *" # every day at 00:00 UTC
  workflow_dispatch:     # allow manual runs too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Fetch Top Played JSON
        run: curl -s https://yye-spotify.onrender.com/api/top-played > top-played.json

      - name: Generate SVG
        run: |
          node -e "
          const fs = require('fs');
          const data = JSON.parse(fs.readFileSync('top-played.json', 'utf8'));
          const svg = \`
          <svg xmlns='http://www.w3.org/2000/svg' width='600' height='200'>
            <style>
              text { font-family: sans-serif; font-size: 16px; }
            </style>
            <text x='10' y='30'>Top Played Tracks:</text>
            \${data.items.map((item, i) => \`
              <text x='10' y='\${60 + i * 30}'>\${item.track} by \${item.artist} - \${item.plays} plays</text>
            \`).join('')}
          </svg>
          \`;
          fs.writeFileSync('top-played.svg', svg);
          "
      - name: Generate SVG
        run: |
          node -e "
          const fs = require('fs');
          const data = JSON.parse(fs.readFileSync('top-played.json', 'utf8'));
          const items = Array.isArray(data) ? data : data.items || [];
          const svg = \`
          <svg xmlns='http://www.w3.org/2000/svg' width='600' height='\${60 + items.length * 30}'>
            <style>
              text { font-family: sans-serif; font-size: 16px; }
            </style>
            <text x='10' y='30'>Top Played Tracks:</text>
            \${items.length > 0 
              ? items.map((item, i) => {
                const track = item.name || 'Unknown Track';
                const artist = item.artists && item.artists.length > 0 ? item.artists.map(a => a.name).join(', ') : 'Unknown Artist';
                const popularity = item.popularity !== undefined ? item.popularity : 'N/A';
                return \`<text x='10' y='\${60 + i * 30}'>\${track} by \${artist} (Popularity: \${popularity})</text>\`;
              }).join('')
              : \`<text x='10' y='60'>No data available.</text>\`
            }
          </svg>
          \`;
          fs.writeFileSync('top-played.svg', svg);
          "
