name: Update top tracks

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate top-tracks.svg
        uses: lowlighter/metrics@latest
        with:
          filename: top-tracks.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: top
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_limit: 5
          plugin_music_playlist: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run markdown updater script
        run: node update-top-tracks.js

      - name: Commit README.md changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "update markdown top tracks" || echo "no changes to commit"
          git push
